-- ============================================================
-- L7VP 达梦 DM8 数据库建表脚本 (v2.1)
-- Schema: DIG_GEO (替代旧 L7VP_PROJECTS)
-- 表数量: 9 张
--
-- 【本脚本是幂等的：可以反复执行，已有的一律不建、不改、不删】
--   · 模式不存在 → 建；已存在 → 跳过   (CREATE SCHEMA IF NOT EXISTS)
--   · 表不存在   → 建；已存在 → 跳过   (CREATE TABLE  IF NOT EXISTS)
--   · 索引不存在 → 建；已存在 → 跳过   (CREATE INDEX  IF NOT EXISTS)
--   · 唯一会被写数据的只有 TILE_CONFIG 的默认瓦片那一行，
--     且只在**缺行**时插入——已有配置（用户可能在页面里改过底图）不会被覆盖。
--
-- 【执行前想先看现状】先单独跑这一句，看 9 张表建了几张：
--   SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'DIG_GEO' ORDER BY TABLE_NAME;
--   9 张都在 → 说明已经建过，本脚本跑下去不会产生任何改动（跑也无害）。
-- （有的达梦版本没有 ALL_TABLES，可换 DBA_TABLES，或看 SYSOBJECTS。）
--
-- 【执行方式】整个文件贴进达梦客户端（DM Manager / disql）执行即可。
--   脚本内表名全部带 DIG_GEO. 前缀，因此与当前连接所在的模式无关。
--   脚本最后一条是只读的核对查询，会把 9 张表的在位情况列出来。
--
-- 【万一客户端报语法错】只可能是 IF NOT EXISTS 不被你那个达梦版本接受
--   （本脚本用的写法与仓库里原来那份 v2.0 完全一致，线上库就是用它建的，正常不会报）。
--   处理办法：手工把模式建出来（CREATE SCHEMA DIG_GEO;），再把脚本里
--   CREATE … IF NOT EXISTS 的 IF NOT EXISTS 去掉，并只挑没建过的表执行。
-- ============================================================

-- 创建 Schema（没有才建）
CREATE SCHEMA IF NOT EXISTS DIG_GEO;

-- ============================================================
-- 1. PROJECTS — 项目主表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.PROJECTS (
  PROJECT_ID        VARCHAR(50)  PRIMARY KEY,
  PROJECT_NAME      VARCHAR(200),
  DESCRIPTION       VARCHAR(500),
  CREATE_TIME       VARCHAR(50),
  UPDATE_TIME       VARCHAR(50),
  THUMBNAIL         VARCHAR(500),
  ASSET_PACKAGE_IDS VARCHAR(500),
  MAP_CONFIG        VARCHAR(4000)
);

CREATE INDEX IF NOT EXISTS IDX_PROJECTS_NAME       ON DIG_GEO.PROJECTS(PROJECT_NAME);
CREATE INDEX IF NOT EXISTS IDX_PROJECTS_CREATE_TIME ON DIG_GEO.PROJECTS(CREATE_TIME);

COMMENT ON TABLE DIG_GEO.PROJECTS IS '项目主表';
COMMENT ON COLUMN DIG_GEO.PROJECTS.PROJECT_ID IS '项目ID (UUID)';
COMMENT ON COLUMN DIG_GEO.PROJECTS.PROJECT_NAME IS '项目名称';
COMMENT ON COLUMN DIG_GEO.PROJECTS.DESCRIPTION IS '项目描述';
COMMENT ON COLUMN DIG_GEO.PROJECTS.CREATE_TIME IS '创建时间 (yyyy-MM-dd HH:mm:ss)';
COMMENT ON COLUMN DIG_GEO.PROJECTS.UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN DIG_GEO.PROJECTS.THUMBNAIL IS '缩略图 URL';
COMMENT ON COLUMN DIG_GEO.PROJECTS.ASSET_PACKAGE_IDS IS '资产包ID列表 (JSON数组)';

-- ============================================================
-- 2. DATASETS — 数据集元数据表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.DATASETS (
  DATASET_ID   VARCHAR(50)  PRIMARY KEY,
  PROJECT_ID   VARCHAR(50)  NOT NULL,
  DATASET_NAME VARCHAR(200),
  TYPE         VARCHAR(50),
  METADATA     CLOB,
  FILTER       CLOB,
  CREATE_TIME  VARCHAR(50),

  CONSTRAINT FK_DATASETS_PROJECT
    FOREIGN KEY (PROJECT_ID) REFERENCES DIG_GEO.PROJECTS(PROJECT_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_DATASETS_PROJECT ON DIG_GEO.DATASETS(PROJECT_ID);

COMMENT ON TABLE DIG_GEO.DATASETS IS '数据集元数据表';
COMMENT ON COLUMN DIG_GEO.DATASETS.DATASET_ID IS '数据集ID (UUID)';
COMMENT ON COLUMN DIG_GEO.DATASETS.PROJECT_ID IS '所属项目ID';
COMMENT ON COLUMN DIG_GEO.DATASETS.DATASET_NAME IS '数据集名称';
COMMENT ON COLUMN DIG_GEO.DATASETS.TYPE IS '数据源类型: local / remote / raster-tile / vector-tile / doris';
COMMENT ON COLUMN DIG_GEO.DATASETS.METADATA IS 'JSON, 数据集元信息 (columnsMeta, rowCount 等)';
COMMENT ON COLUMN DIG_GEO.DATASETS.FILTER IS 'JSON, 数据集筛选器配置 (relation, children 等)';
COMMENT ON COLUMN DIG_GEO.DATASETS.CREATE_TIME IS '创建时间';

-- ============================================================
-- 3. DATASET_COLUMNS — 数据集列定义表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.DATASET_COLUMNS (
  COLUMN_ID      VARCHAR(50)  PRIMARY KEY,
  DATASET_ID     VARCHAR(50)  NOT NULL,
  COLUMN_NAME    VARCHAR(200),
  COLUMN_TYPE    VARCHAR(50),
  COLUMN_INDEX   INT,
  COLUMN_COMMENT VARCHAR(500),

  CONSTRAINT FK_COLUMNS_DATASET
    FOREIGN KEY (DATASET_ID) REFERENCES DIG_GEO.DATASETS(DATASET_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_COLUMNS_DATASET ON DIG_GEO.DATASET_COLUMNS(DATASET_ID);

COMMENT ON TABLE DIG_GEO.DATASET_COLUMNS IS '数据集列定义表';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_ID IS '列ID (UUID)';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.DATASET_ID IS '所属数据集ID';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_NAME IS '列名 (如"城市", "人口")';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_TYPE IS '数据类型: string / number / boolean / date';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_INDEX IS '列序号 (0开始), 对应 row_data JSON数组下标';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_COMMENT IS '字段注释 (数据库 REMARKS)';

-- ============================================================
-- 4. DATASET_ROWS — 数据行表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.DATASET_ROWS (
  ROW_ID     VARCHAR(50)  PRIMARY KEY,
  DATASET_ID VARCHAR(50)  NOT NULL,
  ROW_INDEX  INT,
  ROW_DATA   CLOB,

  CONSTRAINT FK_ROWS_DATASET
    FOREIGN KEY (DATASET_ID) REFERENCES DIG_GEO.DATASETS(DATASET_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_ROWS_DATASET ON DIG_GEO.DATASET_ROWS(DATASET_ID, ROW_INDEX);

COMMENT ON TABLE DIG_GEO.DATASET_ROWS IS '数据行表';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.ROW_ID IS '行ID (UUID)';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.DATASET_ID IS '所属数据集ID';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.ROW_INDEX IS '行序号 (0开始)';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.ROW_DATA IS 'JSON数组, 按 column_index 顺序存储值';

-- ============================================================
-- 5. LAYERS — 图层表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.LAYERS (
  LAYER_ID    VARCHAR(50)  PRIMARY KEY,
  PROJECT_ID  VARCHAR(50)  NOT NULL,
  DATASET_ID  VARCHAR(50),
  LAYER_NAME  VARCHAR(200),
  TYPE        VARCHAR(50),
  VIS_CONFIG  CLOB,
  LAYER_ORDER INT,
  CREATE_TIME VARCHAR(50),

  CONSTRAINT FK_LAYERS_PROJECT
    FOREIGN KEY (PROJECT_ID) REFERENCES DIG_GEO.PROJECTS(PROJECT_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_LAYERS_DATASET
    FOREIGN KEY (DATASET_ID) REFERENCES DIG_GEO.DATASETS(DATASET_ID)
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_LAYERS_PROJECT ON DIG_GEO.LAYERS(PROJECT_ID, LAYER_ORDER);

COMMENT ON TABLE DIG_GEO.LAYERS IS '图层配置表';
COMMENT ON COLUMN DIG_GEO.LAYERS.LAYER_ID IS '图层ID (UUID)';
COMMENT ON COLUMN DIG_GEO.LAYERS.PROJECT_ID IS '所属项目ID';
COMMENT ON COLUMN DIG_GEO.LAYERS.DATASET_ID IS '关联数据集ID (可选)';
COMMENT ON COLUMN DIG_GEO.LAYERS.LAYER_NAME IS '图层名称';
COMMENT ON COLUMN DIG_GEO.LAYERS.TYPE IS '图层类型: BubbleLayer / TileLayer / IconLayer / FlowLayer 等';
COMMENT ON COLUMN DIG_GEO.LAYERS.VIS_CONFIG IS 'JSON, 可视化配置 (颜色、半径、透明度、图标等)';
COMMENT ON COLUMN DIG_GEO.LAYERS.LAYER_ORDER IS '图层叠放顺序';
COMMENT ON COLUMN DIG_GEO.LAYERS.CREATE_TIME IS '创建时间';

-- ============================================================
-- 6. WIDGETS — 组件表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.WIDGETS (
  WIDGET_ID    VARCHAR(50)  PRIMARY KEY,
  PROJECT_ID   VARCHAR(50)  NOT NULL,
  CONTAINER_ID VARCHAR(50),
  WIDGET_NAME  VARCHAR(200),
  TYPE         VARCHAR(50),
  PROPERTIES   CLOB,
  SLOT         VARCHAR(50),
  WIDGET_ORDER INT,

  CONSTRAINT FK_WIDGETS_PROJECT
    FOREIGN KEY (PROJECT_ID) REFERENCES DIG_GEO.PROJECTS(PROJECT_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_WIDGETS_CONTAINER
    FOREIGN KEY (CONTAINER_ID) REFERENCES DIG_GEO.WIDGETS(WIDGET_ID)
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_WIDGETS_PROJECT ON DIG_GEO.WIDGETS(PROJECT_ID, WIDGET_ORDER);

COMMENT ON TABLE DIG_GEO.WIDGETS IS '组件配置表';
COMMENT ON COLUMN DIG_GEO.WIDGETS.WIDGET_ID IS '组件ID (UUID)';
COMMENT ON COLUMN DIG_GEO.WIDGETS.PROJECT_ID IS '所属项目ID';
COMMENT ON COLUMN DIG_GEO.WIDGETS.CONTAINER_ID IS '父容器组件ID (可选, 自引用)';
COMMENT ON COLUMN DIG_GEO.WIDGETS.WIDGET_NAME IS '组件名称';
COMMENT ON COLUMN DIG_GEO.WIDGETS.TYPE IS '组件类型: AnalysisLayout / ZoomControl / Legend 等';
COMMENT ON COLUMN DIG_GEO.WIDGETS.PROPERTIES IS 'JSON, 组件属性配置';
COMMENT ON COLUMN DIG_GEO.WIDGETS.SLOT IS '插槽名 (如 controls)';
COMMENT ON COLUMN DIG_GEO.WIDGETS.WIDGET_ORDER IS '排序序号';

-- ============================================================
-- 7. TILE_CONFIG — 瓦片全局配置表 (单例)
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.TILE_CONFIG (
  ID          VARCHAR(10)  PRIMARY KEY,
  TILE_URL    VARCHAR(500),
  TILE_NAME   VARCHAR(100),
  MIN_ZOOM    INT,
  MAX_ZOOM    INT,
  UPDATE_TIME VARCHAR(50),
  IS_DEFAULT  VARCHAR(10),
  DEFAULT_NUM INT,
  CRS         VARCHAR(50),
  TILE_SCHEME VARCHAR(50),
  ORIGIN      VARCHAR(100)
);

COMMENT ON TABLE DIG_GEO.TILE_CONFIG IS '瓦片全局配置表 (仅1条记录)';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.ID IS '主键, 固定值 "default", 单例';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.TILE_URL IS 'XYZ瓦片地址模板 (含 {x} {y} {z} 占位符)';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.TILE_NAME IS '底图显示名称 (如 "内网卫星影像")';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.MIN_ZOOM IS '最小缩放级别, 默认0';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.MAX_ZOOM IS '最大缩放级别, 默认18';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.IS_DEFAULT IS '是否默认瓦片: 1=是';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.DEFAULT_NUM IS '默认瓦片排序编号';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.CRS IS '坐标系类型: EPSG:3857 或 EPSG:4326';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.TILE_SCHEME IS '瓦片编号方式: XYZ 或 TMS';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.ORIGIN IS '瓦片原点: lng,lat 格式';

-- 插入默认瓦片配置 (高德公开瓦片, 兜底)
-- 语义 = 「缺这一行才插」：底图地址可以在项目页「底图配置」里改并存回这张表，
-- 重跑本脚本**不会**把它冲回高德。
-- 用 INSERT … WHERE NOT EXISTS 而不是 MERGE：效果一样，但不依赖 MERGE 的单分支写法，
-- 任何达梦版本都不会有方言问题。
INSERT INTO DIG_GEO.TILE_CONFIG (ID, TILE_URL, TILE_NAME, MIN_ZOOM, MAX_ZOOM, UPDATE_TIME)
SELECT 'default',
       'https://webrd0{1-4}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}',
       '高德标准地图',
       0,
       18,
       TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIG_GEO.TILE_CONFIG WHERE ID = 'default');

-- ============================================================
-- 8. ICON_CATEGORIES — 图标分类表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.ICON_CATEGORIES (
  CATEGORY_ID   VARCHAR(50)  PRIMARY KEY,
  CATEGORY_NAME VARCHAR(100),
  SORT_ORDER    INT,
  CREATE_TIME   VARCHAR(50)
);

COMMENT ON TABLE DIG_GEO.ICON_CATEGORIES IS '图标分类表';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.CATEGORY_ID IS '分类ID (UUID)';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.CATEGORY_NAME IS '分类名称 (如 "通信", "军事", "交通")';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.SORT_ORDER IS '排序序号';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.CREATE_TIME IS '创建时间';

-- ============================================================
-- 9. ICONS — 图标元数据表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.ICONS (
  ICON_ID       VARCHAR(50)  PRIMARY KEY,
  CATEGORY_ID   VARCHAR(50)  NOT NULL,
  LIBRARY_CODE  VARCHAR(100),
  CODE_NAME     VARCHAR(100),
  FILE_NAME     VARCHAR(500),
  ORIGINAL_NAME VARCHAR(500),
  FILE_TYPE     VARCHAR(20),
  FILE_SIZE     BIGINT,
  URL           VARCHAR(500),
  SORT_ORDER    INT,
  CREATE_TIME   VARCHAR(50),

  CONSTRAINT FK_ICONS_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES DIG_GEO.ICON_CATEGORIES(CATEGORY_ID)
    ON DELETE CASCADE,

  CONSTRAINT UNQ_ICON_CODE UNIQUE (CATEGORY_ID, LIBRARY_CODE, CODE_NAME)
);

CREATE INDEX IF NOT EXISTS IDX_ICONS_CATEGORY ON DIG_GEO.ICONS(CATEGORY_ID, SORT_ORDER);
CREATE INDEX IF NOT EXISTS IDX_ICONS_LOOKUP   ON DIG_GEO.ICONS(LIBRARY_CODE, CODE_NAME);

COMMENT ON TABLE DIG_GEO.ICONS IS '图标元数据表';
COMMENT ON COLUMN DIG_GEO.ICONS.ICON_ID IS '图标ID (UUID)';
COMMENT ON COLUMN DIG_GEO.ICONS.CATEGORY_ID IS '所属分类ID';
COMMENT ON COLUMN DIG_GEO.ICONS.LIBRARY_CODE IS '库号 (用户自定义)';
COMMENT ON COLUMN DIG_GEO.ICONS.CODE_NAME IS '代号 (用户自定义)';
COMMENT ON COLUMN DIG_GEO.ICONS.FILE_NAME IS '服务器存储文件名 (UUID重命名)';
COMMENT ON COLUMN DIG_GEO.ICONS.ORIGINAL_NAME IS '原始文件名';
COMMENT ON COLUMN DIG_GEO.ICONS.FILE_TYPE IS '文件类型: svg / png / jpg 等';
COMMENT ON COLUMN DIG_GEO.ICONS.FILE_SIZE IS '文件大小 (字节)';
COMMENT ON COLUMN DIG_GEO.ICONS.URL IS '图标访问 URL (如 /icons/{categoryId}/{uuid}.{ext})';
COMMENT ON COLUMN DIG_GEO.ICONS.SORT_ORDER IS '分类内排序序号';
COMMENT ON COLUMN DIG_GEO.ICONS.CREATE_TIME IS '创建时间';

-- ============================================================
-- 10. DB_CONNECTIONS — 外部数据源连接配置表
--     原本只写在 doc/sql/v2-new-tables.sql 里，照本文件建库的新环境会漏掉这张表，
--     导致 /api/db-connections/* 全部报「无效的表或视图名」，故并入本文件。
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.DB_CONNECTIONS (
  CONN_ID       VARCHAR(50)  PRIMARY KEY,
  CONN_NAME     VARCHAR(200) NOT NULL,
  DB_TYPE       VARCHAR(50)  NOT NULL,
  HOST          VARCHAR(200) NOT NULL,
  PORT          INT          NOT NULL,
  USERNAME      VARCHAR(200) NOT NULL,
  PASSWORD      VARCHAR(500) NOT NULL,
  -- 关系库：模式名/数据库名；Redis：库序号(0-15)，留空按 0
  SCHEMA_NAME   VARCHAR(200),
  CREATE_TIME   VARCHAR(50),
  UPDATE_TIME   VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS IDX_DB_CONN_NAME ON DIG_GEO.DB_CONNECTIONS(CONN_NAME);

COMMENT ON TABLE DIG_GEO.DB_CONNECTIONS IS '外部数据源连接配置表';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.CONN_ID IS '连接ID (UUID)';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.CONN_NAME IS '连接名称 (用户自定义)';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.DB_TYPE IS '数据源类型: Dameng / Doris / MySQL / PostgreSQL / Redis';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.HOST IS '主机IP地址';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.PORT IS '端口号';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.USERNAME IS '用户名 (Redis 无 ACL 时留空)';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.PASSWORD IS '密码 (内网明文存储)';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.SCHEMA_NAME IS '模式名/数据库名 (Redis 为库序号)';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.CREATE_TIME IS '创建时间 (yyyy-MM-dd HH:mm:ss)';
COMMENT ON COLUMN DIG_GEO.DB_CONNECTIONS.UPDATE_TIME IS '最后修改时间 (yyyy-MM-dd HH:mm:ss)';

-- 老库升级说明：表若已存在，上面的 CREATE 会跳过、COMMENT 仍会重新打一遍，重复执行无副作用。
-- 老库里 DB_TYPE 存成 'MySQL' 但实际连的是 Doris 的连接仍可正常使用（二者同走 MySQL 协议），
-- 只是列表里会显示为 MySQL；需要统一显示时，在页面上把该连接的「数据源类型」重选为 Doris 保存一次即可。

-- ============================================================
-- 执行结果核对（只读，不改任何东西；只是把 10 张表的在位情况查出来）
-- 期望看到 10 行：PROJECTS / DATASETS / DATASET_COLUMNS / DATASET_ROWS /
--               LAYERS / WIDGETS / TILE_CONFIG / ICON_CATEGORIES / ICONS / DB_CONNECTIONS
-- 少哪张说明那张没建成功，往上翻该表的建表语句看报错。
-- 若客户端不认识 ALL_TABLES，换成 DBA_TABLES，或直接删掉本段（不影响建表结果）。
-- ============================================================
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'DIG_GEO' ORDER BY TABLE_NAME;
